name: Java CI - Release

on:
  push:
    tags:
      - v*

jobs:
  create:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - run: ./mvnw --batch-mode clean install
      - run: mkdir release && cp target/*.jar release
      - run: zip release/out.zip -j -r release
      - name: Create GitHub Release
        id: create-github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-github-release.outputs.upload_url }}
          asset_path: release/out.zip
          asset_name: release-artifacts.zip
          asset_content_type: application/zip
