name: CI - Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Maven clean package
        run: ./mvnw --batch-mode clean package
      - name: Prepare release directory
        run: mkdir release && cp target/*.jar release
      - name: Zip release directory
        run: zip release/out.zip -j -r release
      - name: Create GitHub release
        id: create-github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-github-release.outputs.upload_url }}
          asset_path: release/out.zip
          asset_name: release-artifacts.zip
          asset_content_type: application/zip
